/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as apiUploadRouteRouteImport } from './routes/(api)/upload/route'
import { Route as apiCacheRouteRouteImport } from './routes/(api)/cache/route'
import { Route as apiUploadInitRouteImport } from './routes/(api)/upload/init'
import { Route as apiUploadChunkRouteImport } from './routes/(api)/upload/chunk'
import { Route as apiCacheKeyRouteImport } from './routes/(api)/cache/$key'
import { Route as apiBinIdRouteImport } from './routes/(api)/bin/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const apiUploadRouteRoute = apiUploadRouteRouteImport.update({
  id: '/(api)/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const apiCacheRouteRoute = apiCacheRouteRouteImport.update({
  id: '/(api)/cache',
  path: '/cache',
  getParentRoute: () => rootRouteImport,
} as any)
const apiUploadInitRoute = apiUploadInitRouteImport.update({
  id: '/init',
  path: '/init',
  getParentRoute: () => apiUploadRouteRoute,
} as any)
const apiUploadChunkRoute = apiUploadChunkRouteImport.update({
  id: '/chunk',
  path: '/chunk',
  getParentRoute: () => apiUploadRouteRoute,
} as any)
const apiCacheKeyRoute = apiCacheKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => apiCacheRouteRoute,
} as any)
const apiBinIdRoute = apiBinIdRouteImport.update({
  id: '/(api)/bin/$id',
  path: '/bin/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cache': typeof apiCacheRouteRouteWithChildren
  '/upload': typeof apiUploadRouteRouteWithChildren
  '/bin/$id': typeof apiBinIdRoute
  '/cache/$key': typeof apiCacheKeyRoute
  '/upload/chunk': typeof apiUploadChunkRoute
  '/upload/init': typeof apiUploadInitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cache': typeof apiCacheRouteRouteWithChildren
  '/upload': typeof apiUploadRouteRouteWithChildren
  '/bin/$id': typeof apiBinIdRoute
  '/cache/$key': typeof apiCacheKeyRoute
  '/upload/chunk': typeof apiUploadChunkRoute
  '/upload/init': typeof apiUploadInitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(api)/cache': typeof apiCacheRouteRouteWithChildren
  '/(api)/upload': typeof apiUploadRouteRouteWithChildren
  '/(api)/bin/$id': typeof apiBinIdRoute
  '/(api)/cache/$key': typeof apiCacheKeyRoute
  '/(api)/upload/chunk': typeof apiUploadChunkRoute
  '/(api)/upload/init': typeof apiUploadInitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cache'
    | '/upload'
    | '/bin/$id'
    | '/cache/$key'
    | '/upload/chunk'
    | '/upload/init'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cache'
    | '/upload'
    | '/bin/$id'
    | '/cache/$key'
    | '/upload/chunk'
    | '/upload/init'
  id:
    | '__root__'
    | '/'
    | '/(api)/cache'
    | '/(api)/upload'
    | '/(api)/bin/$id'
    | '/(api)/cache/$key'
    | '/(api)/upload/chunk'
    | '/(api)/upload/init'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  apiCacheRouteRoute: typeof apiCacheRouteRouteWithChildren
  apiUploadRouteRoute: typeof apiUploadRouteRouteWithChildren
  apiBinIdRoute: typeof apiBinIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(api)/upload': {
      id: '/(api)/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof apiUploadRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(api)/cache': {
      id: '/(api)/cache'
      path: '/cache'
      fullPath: '/cache'
      preLoaderRoute: typeof apiCacheRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(api)/upload/init': {
      id: '/(api)/upload/init'
      path: '/init'
      fullPath: '/upload/init'
      preLoaderRoute: typeof apiUploadInitRouteImport
      parentRoute: typeof apiUploadRouteRoute
    }
    '/(api)/upload/chunk': {
      id: '/(api)/upload/chunk'
      path: '/chunk'
      fullPath: '/upload/chunk'
      preLoaderRoute: typeof apiUploadChunkRouteImport
      parentRoute: typeof apiUploadRouteRoute
    }
    '/(api)/cache/$key': {
      id: '/(api)/cache/$key'
      path: '/$key'
      fullPath: '/cache/$key'
      preLoaderRoute: typeof apiCacheKeyRouteImport
      parentRoute: typeof apiCacheRouteRoute
    }
    '/(api)/bin/$id': {
      id: '/(api)/bin/$id'
      path: '/bin/$id'
      fullPath: '/bin/$id'
      preLoaderRoute: typeof apiBinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface apiCacheRouteRouteChildren {
  apiCacheKeyRoute: typeof apiCacheKeyRoute
}

const apiCacheRouteRouteChildren: apiCacheRouteRouteChildren = {
  apiCacheKeyRoute: apiCacheKeyRoute,
}

const apiCacheRouteRouteWithChildren = apiCacheRouteRoute._addFileChildren(
  apiCacheRouteRouteChildren,
)

interface apiUploadRouteRouteChildren {
  apiUploadChunkRoute: typeof apiUploadChunkRoute
  apiUploadInitRoute: typeof apiUploadInitRoute
}

const apiUploadRouteRouteChildren: apiUploadRouteRouteChildren = {
  apiUploadChunkRoute: apiUploadChunkRoute,
  apiUploadInitRoute: apiUploadInitRoute,
}

const apiUploadRouteRouteWithChildren = apiUploadRouteRoute._addFileChildren(
  apiUploadRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  apiCacheRouteRoute: apiCacheRouteRouteWithChildren,
  apiUploadRouteRoute: apiUploadRouteRouteWithChildren,
  apiBinIdRoute: apiBinIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
