/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as apiCacheRouteRouteImport } from './routes/(api)/cache/route'
import { Route as apiFoldersRouteRouteImport } from './routes/(api)/folders/route'
import { Route as apiUploadRouteRouteImport } from './routes/(api)/upload/route'
import { Route as apiArchiveBuildsRouteRouteImport } from './routes/(api)/archive/builds/route'
import { Route as apiBinIdRouteImport } from './routes/(api)/bin/$id'
import { Route as apiCacheKeyRouteImport } from './routes/(api)/cache/$key'
import { Route as apiCacheChunkRouteImport } from './routes/(api)/cache/chunk'
import { Route as apiCacheInitRouteImport } from './routes/(api)/cache/init'
import { Route as apiUploadChunkRouteImport } from './routes/(api)/upload/chunk'
import { Route as apiUploadInitRouteImport } from './routes/(api)/upload/init'
import { Route as apiArchiveBuildsBuildIdRouteImport } from './routes/(api)/archive/builds/$buildId'
import { Route as apiArchiveBuildsBuildIdVerifyRouteImport } from './routes/(api)/archive/builds/$buildId.verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const apiCacheRouteRoute = apiCacheRouteRouteImport.update({
  id: '/(api)/cache',
  path: '/cache',
  getParentRoute: () => rootRouteImport,
} as any)
const apiFoldersRouteRoute = apiFoldersRouteRouteImport.update({
  id: '/(api)/folders',
  path: '/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const apiUploadRouteRoute = apiUploadRouteRouteImport.update({
  id: '/(api)/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const apiArchiveBuildsRouteRoute = apiArchiveBuildsRouteRouteImport.update({
  id: '/(api)/archive/builds',
  path: '/archive/builds',
  getParentRoute: () => rootRouteImport,
} as any)
const apiBinIdRoute = apiBinIdRouteImport.update({
  id: '/(api)/bin/$id',
  path: '/bin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const apiCacheKeyRoute = apiCacheKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => apiCacheRouteRoute,
} as any)
const apiCacheChunkRoute = apiCacheChunkRouteImport.update({
  id: '/chunk',
  path: '/chunk',
  getParentRoute: () => apiCacheRouteRoute,
} as any)
const apiCacheInitRoute = apiCacheInitRouteImport.update({
  id: '/init',
  path: '/init',
  getParentRoute: () => apiCacheRouteRoute,
} as any)
const apiUploadChunkRoute = apiUploadChunkRouteImport.update({
  id: '/chunk',
  path: '/chunk',
  getParentRoute: () => apiUploadRouteRoute,
} as any)
const apiUploadInitRoute = apiUploadInitRouteImport.update({
  id: '/init',
  path: '/init',
  getParentRoute: () => apiUploadRouteRoute,
} as any)
const apiArchiveBuildsBuildIdRoute = apiArchiveBuildsBuildIdRouteImport.update({
  id: '/$buildId',
  path: '/$buildId',
  getParentRoute: () => apiArchiveBuildsRouteRoute,
} as any)
const apiArchiveBuildsBuildIdVerifyRoute =
  apiArchiveBuildsBuildIdVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => apiArchiveBuildsBuildIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cache': typeof apiCacheRouteRouteWithChildren
  '/folders': typeof apiFoldersRouteRoute
  '/upload': typeof apiUploadRouteRouteWithChildren
  '/archive/builds': typeof apiArchiveBuildsRouteRouteWithChildren
  '/bin/$id': typeof apiBinIdRoute
  '/cache/$key': typeof apiCacheKeyRoute
  '/cache/chunk': typeof apiCacheChunkRoute
  '/cache/init': typeof apiCacheInitRoute
  '/upload/chunk': typeof apiUploadChunkRoute
  '/upload/init': typeof apiUploadInitRoute
  '/archive/builds/$buildId': typeof apiArchiveBuildsBuildIdRouteWithChildren
  '/archive/builds/$buildId/verify': typeof apiArchiveBuildsBuildIdVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cache': typeof apiCacheRouteRouteWithChildren
  '/folders': typeof apiFoldersRouteRoute
  '/upload': typeof apiUploadRouteRouteWithChildren
  '/archive/builds': typeof apiArchiveBuildsRouteRouteWithChildren
  '/bin/$id': typeof apiBinIdRoute
  '/cache/$key': typeof apiCacheKeyRoute
  '/cache/chunk': typeof apiCacheChunkRoute
  '/cache/init': typeof apiCacheInitRoute
  '/upload/chunk': typeof apiUploadChunkRoute
  '/upload/init': typeof apiUploadInitRoute
  '/archive/builds/$buildId': typeof apiArchiveBuildsBuildIdRouteWithChildren
  '/archive/builds/$buildId/verify': typeof apiArchiveBuildsBuildIdVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(api)/cache': typeof apiCacheRouteRouteWithChildren
  '/(api)/folders': typeof apiFoldersRouteRoute
  '/(api)/upload': typeof apiUploadRouteRouteWithChildren
  '/(api)/archive/builds': typeof apiArchiveBuildsRouteRouteWithChildren
  '/(api)/bin/$id': typeof apiBinIdRoute
  '/(api)/cache/$key': typeof apiCacheKeyRoute
  '/(api)/cache/chunk': typeof apiCacheChunkRoute
  '/(api)/cache/init': typeof apiCacheInitRoute
  '/(api)/upload/chunk': typeof apiUploadChunkRoute
  '/(api)/upload/init': typeof apiUploadInitRoute
  '/(api)/archive/builds/$buildId': typeof apiArchiveBuildsBuildIdRouteWithChildren
  '/(api)/archive/builds/$buildId/verify': typeof apiArchiveBuildsBuildIdVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cache'
    | '/folders'
    | '/upload'
    | '/archive/builds'
    | '/bin/$id'
    | '/cache/$key'
    | '/cache/chunk'
    | '/cache/init'
    | '/upload/chunk'
    | '/upload/init'
    | '/archive/builds/$buildId'
    | '/archive/builds/$buildId/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cache'
    | '/folders'
    | '/upload'
    | '/archive/builds'
    | '/bin/$id'
    | '/cache/$key'
    | '/cache/chunk'
    | '/cache/init'
    | '/upload/chunk'
    | '/upload/init'
    | '/archive/builds/$buildId'
    | '/archive/builds/$buildId/verify'
  id:
    | '__root__'
    | '/'
    | '/(api)/cache'
    | '/(api)/folders'
    | '/(api)/upload'
    | '/(api)/archive/builds'
    | '/(api)/bin/$id'
    | '/(api)/cache/$key'
    | '/(api)/cache/chunk'
    | '/(api)/cache/init'
    | '/(api)/upload/chunk'
    | '/(api)/upload/init'
    | '/(api)/archive/builds/$buildId'
    | '/(api)/archive/builds/$buildId/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  apiCacheRouteRoute: typeof apiCacheRouteRouteWithChildren
  apiFoldersRouteRoute: typeof apiFoldersRouteRoute
  apiUploadRouteRoute: typeof apiUploadRouteRouteWithChildren
  apiArchiveBuildsRouteRoute: typeof apiArchiveBuildsRouteRouteWithChildren
  apiBinIdRoute: typeof apiBinIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(api)/cache': {
      id: '/(api)/cache'
      path: '/cache'
      fullPath: '/cache'
      preLoaderRoute: typeof apiCacheRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(api)/folders': {
      id: '/(api)/folders'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof apiFoldersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(api)/upload': {
      id: '/(api)/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof apiUploadRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(api)/archive/builds': {
      id: '/(api)/archive/builds'
      path: '/archive/builds'
      fullPath: '/archive/builds'
      preLoaderRoute: typeof apiArchiveBuildsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(api)/bin/$id': {
      id: '/(api)/bin/$id'
      path: '/bin/$id'
      fullPath: '/bin/$id'
      preLoaderRoute: typeof apiBinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(api)/cache/$key': {
      id: '/(api)/cache/$key'
      path: '/$key'
      fullPath: '/cache/$key'
      preLoaderRoute: typeof apiCacheKeyRouteImport
      parentRoute: typeof apiCacheRouteRoute
    }
    '/(api)/cache/chunk': {
      id: '/(api)/cache/chunk'
      path: '/chunk'
      fullPath: '/cache/chunk'
      preLoaderRoute: typeof apiCacheChunkRouteImport
      parentRoute: typeof apiCacheRouteRoute
    }
    '/(api)/cache/init': {
      id: '/(api)/cache/init'
      path: '/init'
      fullPath: '/cache/init'
      preLoaderRoute: typeof apiCacheInitRouteImport
      parentRoute: typeof apiCacheRouteRoute
    }
    '/(api)/upload/chunk': {
      id: '/(api)/upload/chunk'
      path: '/chunk'
      fullPath: '/upload/chunk'
      preLoaderRoute: typeof apiUploadChunkRouteImport
      parentRoute: typeof apiUploadRouteRoute
    }
    '/(api)/upload/init': {
      id: '/(api)/upload/init'
      path: '/init'
      fullPath: '/upload/init'
      preLoaderRoute: typeof apiUploadInitRouteImport
      parentRoute: typeof apiUploadRouteRoute
    }
    '/(api)/archive/builds/$buildId': {
      id: '/(api)/archive/builds/$buildId'
      path: '/$buildId'
      fullPath: '/archive/builds/$buildId'
      preLoaderRoute: typeof apiArchiveBuildsBuildIdRouteImport
      parentRoute: typeof apiArchiveBuildsRouteRoute
    }
    '/(api)/archive/builds/$buildId/verify': {
      id: '/(api)/archive/builds/$buildId/verify'
      path: '/verify'
      fullPath: '/archive/builds/$buildId/verify'
      preLoaderRoute: typeof apiArchiveBuildsBuildIdVerifyRouteImport
      parentRoute: typeof apiArchiveBuildsBuildIdRoute
    }
  }
}

interface apiCacheRouteRouteChildren {
  apiCacheKeyRoute: typeof apiCacheKeyRoute
  apiCacheChunkRoute: typeof apiCacheChunkRoute
  apiCacheInitRoute: typeof apiCacheInitRoute
}

const apiCacheRouteRouteChildren: apiCacheRouteRouteChildren = {
  apiCacheKeyRoute: apiCacheKeyRoute,
  apiCacheChunkRoute: apiCacheChunkRoute,
  apiCacheInitRoute: apiCacheInitRoute,
}

const apiCacheRouteRouteWithChildren = apiCacheRouteRoute._addFileChildren(
  apiCacheRouteRouteChildren,
)

interface apiUploadRouteRouteChildren {
  apiUploadChunkRoute: typeof apiUploadChunkRoute
  apiUploadInitRoute: typeof apiUploadInitRoute
}

const apiUploadRouteRouteChildren: apiUploadRouteRouteChildren = {
  apiUploadChunkRoute: apiUploadChunkRoute,
  apiUploadInitRoute: apiUploadInitRoute,
}

const apiUploadRouteRouteWithChildren = apiUploadRouteRoute._addFileChildren(
  apiUploadRouteRouteChildren,
)

interface apiArchiveBuildsBuildIdRouteChildren {
  apiArchiveBuildsBuildIdVerifyRoute: typeof apiArchiveBuildsBuildIdVerifyRoute
}

const apiArchiveBuildsBuildIdRouteChildren: apiArchiveBuildsBuildIdRouteChildren =
  {
    apiArchiveBuildsBuildIdVerifyRoute: apiArchiveBuildsBuildIdVerifyRoute,
  }

const apiArchiveBuildsBuildIdRouteWithChildren =
  apiArchiveBuildsBuildIdRoute._addFileChildren(
    apiArchiveBuildsBuildIdRouteChildren,
  )

interface apiArchiveBuildsRouteRouteChildren {
  apiArchiveBuildsBuildIdRoute: typeof apiArchiveBuildsBuildIdRouteWithChildren
}

const apiArchiveBuildsRouteRouteChildren: apiArchiveBuildsRouteRouteChildren = {
  apiArchiveBuildsBuildIdRoute: apiArchiveBuildsBuildIdRouteWithChildren,
}

const apiArchiveBuildsRouteRouteWithChildren =
  apiArchiveBuildsRouteRoute._addFileChildren(
    apiArchiveBuildsRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  apiCacheRouteRoute: apiCacheRouteRouteWithChildren,
  apiFoldersRouteRoute: apiFoldersRouteRoute,
  apiUploadRouteRoute: apiUploadRouteRouteWithChildren,
  apiArchiveBuildsRouteRoute: apiArchiveBuildsRouteRouteWithChildren,
  apiBinIdRoute: apiBinIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
